[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm run dev"
healthcheckPath = "/info"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
NODE_ENV = "production" 