[build]
builder = "nixpacks"
buildCommand = "npm install -g corepack@0.24.1 && corepack enable && pnpm install && pnpm build"

[deploy]
startCommand = "pnpm dev"
healthcheckPath = "/info"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
NODE_ENV = "production" 