[build]
builder = "nixpacks"
buildCommand = "cd apps/agents && pnpm install && pnpm build"

[deploy]
startCommand = "cd apps/agents && pnpm start"
healthcheckPath = "/info"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
NODE_ENV = "production" 