[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm && export PATH=$PATH:/usr/local/bin && pnpm install && pnpm build"

[deploy]
startCommand = "export PATH=$PATH:/usr/local/bin && pnpm start"
healthcheckPath = "/info"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
NODE_ENV = "production" 