[build]
builder = "nixpacks"
buildCommand = "cd /app && pnpm install && cd /app/apps/agents && pnpm build"

[deploy]
startCommand = "cd /app/apps/agents && pnpm start"
healthcheckPath = "/info"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 