[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm && pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/info"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
NODE_ENV = "production" 