[build]
builder = "nixpacks"
buildCommand = "cd ../.. && corepack enable && corepack prepare pnpm@10.6.3 --activate && pnpm install && cd apps/agents && pnpm build:internal"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/info"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
NODE_ENV = "production" 