[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install && cd apps/agents && pnpm build"

[deploy]
startCommand = "cd apps/agents && pnpm start"
healthcheckPath = "/info"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 