[build]
builder = "nixpacks"
buildCommand = "cd ../.. && npm install && cd apps/agents && npm run build:internal"

[deploy]
startCommand = "npm start"
healthcheckPath = "/info"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
NODE_ENV = "production" 